/* User/Auth Actions */
export const GOOGLE_OAUTH_LOGIN = "GOOGLE_OAUTH_LOGIN";
export const GOOGLE_OAUTH_ERROR = "GOOGLE_OAUTH_ERROR";
export const GOOGLE_OAUTH_SIGNOUT = "GOOGLE_OAUTH_SIGNOUT";
export const GET_PROFILE_INFO_SUCCESS = "GET_PROFILE_INFO_SUCCESS";
export const GET_PROFILE_INFO_ERROR = "GET_PROFILE_INFO_ERROR";

/* Playlist Actions */
export const GET_USER_PLAYLISTS = "GET_USER_PLAYLISTS";
export const GET_USER_PLAYLISTS_ERROR = "GET_OWN_PLAYLISTS_ERROR";
export const CREATE_USER_PLAYLIST = "CREATE_USER_PLAYLIST";
export const CREATE_USER_PLAYLIST_ERROR = "CREATE_USER_PLAYLIST_ERROR";
export const EDIT_USER_PLAYLIST = "EDIT_USER_PLAYLIST";
export const EDIT_USER_PLAYLIST_ERROR = "EDIT_USER_PLAYLIST_ERROR";
export const DELETE_USER_PLAYLIST = "DELETE_USER_PLAYLIST";
export const DELETE_USER_PLAYLIST_ERROR = "DELETE_USER_PLAYLIST_ERROR";

/* Video Actions */
export const GET_PLAYLIST_VIDEOS = "GET_PLAYLIST_VIDEOS";
export const GET_PLAYLIST_VIDEOS_ERROR = "GET_PLAYLIST_VIDEOS_ERROR";
export const ADD_PLAYLIST_VIDEO = "ADD_PLAYLIST_VIDEO";
export const ADD_PLAYLIST_VIDEOS_ERROR = "ADD_PLAYLIST_VIDEO_ERROR";
export const EDIT_PLAYLIST_VIDEO = "EDIT_PLAYLIST_VIDEO";
export const EDIT_PLAYLIST_VIDEOS_ERROR = "EDIT_PLAYLIST_VIDEO_ERROR";
export const DELETE_PLAYLIST_VIDEO = "DELETE_PLAYLIST_VIDEO";
export const DELETE_PLAYLIST_VIDEOS_ERROR = "DELETE_PLAYLIST_VIDEO_ERROR";

/* Player Actions */
export const TOGGLE_PLAYER = "TOGGLE_PLAYER";
export const SET_PLAYER_VOLUME = "SET_PLAYER_VOLUME";
export const SET_ACTIVE_ITEM = "SET_ACTIVE_ITEM";
export const ADD_PLAYBACK_ITEM = "ADD_PLAYBACK_ITEM";
export const REMOVE_PLAYBACK_ITEM = "REMOVE_PLAYBACK_ITEM";

/* YouTube Actions */
export const GET_YOUTUBE_VIDEO = "GET_YOUTUBE_VIDEO";
export const GET_YOUTUBE_VIDEO_ERROR = "GET_YOUTUBE_VIDEO_ERROR";

/* Meta Data (EchoTube API) Actions */

export const GET_METADATA = "GET_METADATA";
export const GET_METADATA_ERROR = "GET_METADATA_ERROR";

/* Deezer Actions */

export const GET_DEEZER_BY_NAME = "GET_DEEZER_BY_NAME";
export const GET_DEEZER_BY_NAME_ERROR = "GET_DEEZER_BY_NAME_ERROR";
